name: Build and Push (Maven / Amazon Corretto 22)

on:
  push:
    branches: [ main ]
    paths: 
      - dockerfiles/maven-amazoncorretto-22/dockerfile
  pull_request:
    branches: [ main ]
    paths: 
      - dockerfiles/maven-amazoncorretto-22/dockerfile
  schedule:
    - cron: '0 0 * * *'  # every day at midnight 

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/maven-amazoncorretto-22/dockerfile
        push: true
        tags: |
          daniiiol/dependency-check-maven-prepared:latest
          daniiiol/dependency-check-maven-prepared:amazoncorretto-22
